# -*- coding: utf-8 -*-
"""P1_Forrest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zj2-wJaTmKlY6Sa5E2ekqzDKZaSvokxT

---

```
CISC 3440: Machine Learning
P1 (25+5 Points)
Due: Oct 7th, 11:59 pm
```
---
**Submission Instructions**


* You are expected to complete this project on your own (not with a partner).
* Please refer to the syllabus for the late submission policy.
* You must submit your assignment via Blackboard.
* Your code should work without errors; code that fails will not be graded.


We will work on Kaggle competition Dataset (https://www.kaggle.com/competitions/titanic/data?select=train.csv) for this project. You will use Decistion Tree Classifer to predict if a passenger on Titanic ship would survive or not. You are provided with one file train.csv to build your Tree. You are also provided with some started code to read files and process them.

**Data Features:** Each line in the file has the following Features


| Variable  | Definition                                   | Key                                      |
|-----------|----------------------------------------------|------------------------------------------|
| survival  | Survival -Label                                     | 0 = No, 1 = Yes                          |
| pclass    | Ticket class                                 | 1 = 1st, 2 = 2nd, 3 = 3rd                |
| sex       | Sex                                          |                                          |
| Age       | Age in years                                 |                                          |
| sibsp     | # of siblings / spouses aboard the Titanic   |                                          |
| parch     | # of parents / children aboard the Titanic   |                                          |
| fare      | Passenger fare                               |                                          |
| embarked  | Port of Embarkation                          | C = Cherbourg, Q = Queenstown, S = Southampton |

**First Row**

| Survived | Pclass | Sex  | Age | SibSp | Parch | Fare | Embarked |
|----------|--------|------|-----|-------|-------|------|----------|
| 0        | 3      | male | 22  | 1     | 0     | 7.25 | S        |


The function below reads the data and qunatizes them using the following criteria:

    - Pclass: remains as an integer.
    - Sex: 'male' is mapped to 0, 'female' to 1.
    - Age: divided by 10 and truncated to an integer.
    - SibSp: remains as an integer.
    - Parch: remains as an integer.
    - Fare: remains as a floating-point number.
    - Embarked: 'S' is mapped to 0, 'C' to 1, 'Q' to 2, and unknown values to

<u>Feel free to change the quantization in any way you see fit. However, you are not required to make any changes to this part of the code.</u>
"""

# Global Constants for column indices
PCLASS = 0
SEX = 1
AGE = 2
SIBSP = 3
PARCH = 4
FARE = 5
EMBARKED = 6
attribute_list = ["PCLASS", "SEX", "AGE", "SIBSP", "PARCH", "FARE", "EMBARKED"]

import numpy as np

def get_data_and_labels(filename, contains_label=True):
    '''
    This function reads data from a CSV file, processes it, and returns two numpy arrays:
    one with quantized features and another with labels (if labels are present).

    ARGS:

    filename : str
        The path to the CSV file containing the data.

    contains_label : bool, optional
        A flag indicating whether the input file contains labels (default is True).

    Returns:
    quantized_features : list of list
        A list of lists where each inner list contains the quantized features for each data entry.

    labels : list
        A list containing labels for each data entry if `contains_label` is True.

    Note:
    The function assumes that the input CSV file has the following columns in order:
    Pclass, Sex, Age, SibSp, Parch, Fare, and Embarked.

    The quantization process:
    - Pclass: remains as an integer.
    - Sex: 'male' is mapped to 0, 'female' to 1.
    - Age: divided by 10 and truncated to an integer.
    - SibSp: remains as an integer.
    - Parch: remains as an integer.
    - Fare: remains as a floating-point number.
    - Embarked: 'S' is mapped to 0, 'C' to 1, 'Q' to 2, and unknown values to -1.
    '''


    # Open the file and read all lines except the header
    file = open(filename, 'r')
    data = file.readlines()[1:]  # Skip the header

    # Extract labels and features if the file contains labels
    if contains_label:
        labels = [int(x.strip('\n').split(',')[0]) for x in data]
        features = [x.strip('\n').split(',')[1:] for x in data]
    else:
        features = [x.strip('\n').split(',') for x in data]

    quantized_features = []

    # Process each feature and quantize them
    for feature in features:
        quantized_feature = []
        for column in range(len(feature)):
            if column == PCLASS:
                quantized_feature.append(int(feature[column]))  # Pclass: as is
            elif column == SEX:
                if feature[column] == 'male':
                    quantized_feature.append(0)  # Sex: 'male' -> 0
                else:
                    quantized_feature.append(1)  # Sex: 'female' -> 1
            elif column == AGE:
                try:
                    quantized_feature.append(int(float(feature[column]) // 10))  # Age: decade-wise quantization
                except:
                    quantized_feature.append(-1)  # Missing age: represented as -1
            elif column == SIBSP:
                quantized_feature.append(int(feature[column]))  # SibSp: as is
            elif column == PARCH:
                quantized_feature.append(int(feature[column]))  # Parch: as is
            elif column == FARE:
                quantized_feature.append(int(float(feature[column]) // 30))  # Fare: Quantized as multiples of 30
            else:
                # Embarked: map 'S' -> 0, 'C' -> 1, 'Q' -> 2, unknown -> -1
                if feature[column] == 'S':
                    quantized_feature.append(0)
                elif feature[column] == 'C':
                    quantized_feature.append(1)
                elif feature[column] == 'Q':
                    quantized_feature.append(2)
                else:
                    quantized_feature.append(-1)
        quantized_features.append(quantized_feature)

    return quantized_features, labels if contains_label else None

from google.colab import files
uploaded = files.upload()

quantized_features, labels = get_data_and_labels('train.csv')
# Convert to a NumPy array
quantized_features = np.array(quantized_features)
labels = np.array(labels)

print(labels) #labels is whether or not the person survived
print(len(labels))
print(quantized_features)
print(len(quantized_features))

"""**[3 points] Computing Entropy**
The function below has the skeleton for you to fill in the code to compute entropy. Entropy is based on the porbability distribiution of different values for the labels

The entropy \( $H(L)$ \) is defined as:

$H(L) = -\sum_{i=1}^{c} p_i \log_2(p_i)$

where:
- \( $p_i$ \) is the probability of class \( $i$ \),
- \( $c$ \) is the total number of classes.
- L is our label probability distribution

"""

def compute_entropy(labels):
  """
    Computes the entropy of a set of labels.

    Args:
        labels (list or array-like): The list of labels for which entropy is to be computed.

    Returns:
        float: The entropy of the label set.
  """

  entropy=0

  #FILL IN

  # Initialize:
  no_count, yes_count = 0, 0

  # 1. Calculate p(no) and p(yes) for if a person survived
  #     - find the total of each and divide by the total to get the probability
  for label in labels:
    if label == 0:
      no_count += 1
    if label == 1:
      yes_count += 1
  if len(labels) > 0:
    p_no = no_count / len(labels)
    p_yes = yes_count / len(labels)
  else:
    # Entropy will be 0 for empty groups
    return 0

  #2. Calculate -p(no)*log(p(no)) - p(yes)*log(p(yes)) for cases where there is p > 0
  if p_no > 0:
    entropy -= p_no * np.log2(p_no)
  if p_yes > 0:
    entropy -= p_yes * np.log2(p_yes)

  return entropy

print(compute_entropy(labels))

"""
You might find the function below useful for implementing the function to compute information gain in the next section."""

def split_by_feature_value(data, labels, feature_name):
    """
    Splits the dataset into subsets based on unique values of the specified feature.

    ARGS:

    data : np.ndarray
        A 2D numpy array where each row represents a data instance and each column
        represents a feature.
    labels : list or np.ndarray
        A 1D array or list containing the labels corresponding to the data instances.
    feature_name : int
        The index of the feature (column) by which to split the data.

    Returns:

    spilt_labels : dict
        A dictionary where the keys are the unique values of the specified feature, and
        the values are numpy arrays of labels corresponding to each unique feature value.
    """

    # Initialize an empty dictionary to hold the split labels
    spilt_labels = {}
    split_data={}

    # Get the unique values of the specified feature
    feature_values = set(data[:, feature_name].tolist())

    # Iterate over each unique feature value
    for feature_value in feature_values:
        # Get the labels corresponding to the current feature value
        spilt_labels[feature_value] = np.array(labels)[np.argwhere(data[:, feature_name] == feature_value).reshape(-1)].tolist()
        split_data[feature_value]=data[np.argwhere(data[:, feature_name] == feature_value).reshape(-1)]

    return spilt_labels,split_data

pclass_split_labels = split_by_feature_value(quantized_features,labels,0)[0]   #split by Pclass
pclass_split_data = split_by_feature_value(quantized_features,labels,0)[1]
print(pclass_split_labels)
print('---------') #divider
print(pclass_split_data)

"""**[5 points] Computting Information Gain**

$Information Gain(L,A)=Entropy(L)- \sum_v\frac{L_v}{L}Entropy(L_v)$
Where:
  - Entropy (L) - should use the function compute_entropy()
  - L - The labels without split based on attribute values
  - A - is the attribute
  - v - represents the different values that the attribute can take
  - $L_v$ - reprensets the labels correspdoning to the attribute A with value v

Please fill in the code below to compute the information gain for an attribute which is indicate through the feature name
"""

def compute_information_gain(data, labels, feature_name):
  """
    Computes the information gain of a given feature in the dataset.

    Args:
        data (list or array-like): The dataset containing the features.
        labels (list or array-like): The list of labels corresponding to each data point.
        feature_name (str): The name of the feature or attribute for which information gain is computed.

    Returns:
        float: The information gain achieved by splitting the dataset using the given feature.
    """
  information_gain=None

  #FILL IN
  """
  1.
  """
  L = len(labels)
  information_gain = compute_entropy(labels)

  #find the length of the labels produced by the split
  split_labels = split_by_feature_value(quantized_features,labels,feature_name)[0]

  lengths = []
  for value in split_labels.values():
    lengths.append(len(value))
    information_gain -= (len(value)/len(labels))*compute_entropy(value) if compute_entropy(value) != float('nan') else 0
    # print('entropy: ', compute_entropy(value))
    # print('information_gain: ', information_gain)

  # print(split_labels)
  # for i,length in enumerate(lengths):
  #   information_gain -= (length/len(labels))*compute_entropy(split_labels[i + 1])

  return information_gain

for i,attribute in enumerate(attribute_list):
  print(f'Information gain for {attribute}: {compute_information_gain(quantized_features, labels, i)}')

"""**Create Training and Validation Data splits**

The function below will take the dataset and labels and create random splits based on given percentage.
"""

def create_training_validation_split(data,labels,split_percentage):
  """
    Splits a dataset into training and validation sets based on a given split percentage.

    ARGS:
    ----------
    data : numpy.ndarray
       The data to be split into train and validation

    labels : list
        The corresponding labels for the data

    split_percentage : float
        A float between 0 and 1 that specifies the proportion of the dataset to allocate to the training set.
        For example, 0.8 would allocate 80% of the data to the training set and the remaining 20% to the validation set.

    Returns:
    -------
    tuple : (train_features, train_labels, validation_features, validation_labels)
        - train_features : numpy.ndarray
            The feature data for the training set.
        - train_labels : numpy.ndarray
            The corresponding labels for the training set.
        - validation_features : numpy.ndarray
            The feature data for the validation set.
        - validation_labels : numpy.ndarray
            The corresponding labels for the validation set.
  """
  import random
  import numpy as np
  train_features=[]
  train_labels=[]
  validation_features=[]
  validation_labels=[]
  total_sample_count=len(data)
  train_sample_count=int(split_percentage*total_sample_count)
  validation_sample_count=total_sample_count-train_sample_count
  train_indices=random.sample(range(total_sample_count),train_sample_count)
  validation_indices=random.sample(list(set(range(total_sample_count))-set(train_indices)),validation_sample_count)
  for i in range(total_sample_count):
    if i in train_indices:
      train_features.append(data[i])
      train_labels.append(labels[i])
    if i in validation_indices:
      validation_features.append(data[i])
      validation_labels.append(labels[i])
  return np.array(train_features),np.array(train_labels),np.array(validation_features),np.array(validation_labels)

"""** Testing your Functions**

The code below computes the entropy of the entire dataset and the attribute with the highest information gain.
- Q1) [1 point] What is the entropy of the dataset?
- Q2) [1 point] What is the attribute with the highest information gain?

<u>You will type the answers to these questions in a separate text document you will find details for this in the Submission Instructions below </u>

**[15 points] Building the Decision Tree**

Using Sklearn Decision Tree library. Here you will build upon the tutorial we worked in class. You will perform hyper-parameter tuning using the provided data, you can configure and play with any parameter you see fit.

- [5 points] You are expected to provide a brief discussion of the impact of the parameters you choose and what you learned during this process. Your discussion should touch the following topics:

1. What is the impact of depth on the accuracy?
2. Did cross validation help?
3. Did you try other hyperparameters like leaf size and minimum samples to split?

- [10 points] Save the best_model similar to the tuorial as a pickle file you should include this as part of your submission. This is the model that will be run on the test set and your points will be based on that.
"""

import pickle
from sklearn import tree
import graphviz
from IPython.display import Image

quantized_features, labels=get_data_and_labels('train.csv')
train_features,train_labels,validation_features,validation_labels=create_training_validation_split(quantized_features,labels,0.9)

#FILL IN

#Initialize a Decision Tree Classifier with Entropy as the criterion
classifier=tree.DecisionTreeClassifier(criterion='entropy')
#Fit method builds a DecisionTree classifier from the training sample set
classifier.fit(train_features,train_labels)
#Code to visualize the built DTree
dot_data = tree.export_graphviz(classifier, out_file=None)
graph = graphviz.Source(dot_data)
Image(graph.pipe(format='png'))

def accuracy(predictions, labels):
    correct_predictions = 0

    # Iterate over both predictions and labels simultaneously
    for pred, actual in zip(predictions, labels):
        if pred == actual:
            correct_predictions += 1

    # Calculate accuracy as the percentage of correct predictions
    accuracy_percentage = (correct_predictions / len(labels)) * 100
    return accuracy_percentage

#Using the predict method of the classifier to make predictions on the validation_feature
validation_predictions=classifier.predict(validation_features)

# Example usage
validation_accuracy = accuracy(validation_predictions, validation_labels)
print("The accuracy of the current model on the validation set is {:.2f}%".format(validation_accuracy))

#For this classifier in addition to setting the criterion as entropy we also insist that the maximum depth of the tree should be 10
pruned_classifier=tree.DecisionTreeClassifier(criterion='entropy',max_depth=10)
pruned_classifier.fit(train_features,train_labels)
dot_data = tree.export_graphviz(pruned_classifier, out_file=None)
graph = graphviz.Source(dot_data)
Image(graph.pipe(format='png'))

#Using the predict method of the classifier to make predictions on the validation_feature
validation_predictions=pruned_classifier.predict(validation_features)

# Example usage
validation_accuracy = accuracy(validation_predictions, validation_labels)
print("The accuracy of the current model on the validation set is {:.2f}%".format(validation_accuracy))

#For this classifier in addition to setting the criterion as entropy we also insist that the maximum depth of the tree should be 4
pruned_classifier=tree.DecisionTreeClassifier(criterion='entropy',max_depth=4)
pruned_classifier.fit(train_features,train_labels)
dot_data = tree.export_graphviz(pruned_classifier, out_file=None)
graph = graphviz.Source(dot_data)
Image(graph.pipe(format='png'))

#Using the predict method of the classifier to make predictions on the validation_feature
validation_predictions=pruned_classifier.predict(validation_features)

# Example usage
validation_accuracy = accuracy(validation_predictions, validation_labels)
print("The accuracy of the current model on the validation set is {:.2f}%".format(validation_accuracy))

minimum_samples_to_split=[15,30,40]
minimum_samples_at_leaf=[25,30,40]

best_model=None
best_accuracy=0
#We use two for loops to go over the different possible combinations of split and leaf samples
for split in minimum_samples_to_split:
  for leaf in minimum_samples_at_leaf:
    pruned_classifier=tree.DecisionTreeClassifier(criterion='entropy',min_samples_split=split,min_samples_leaf=leaf)
    pruned_classifier.fit(train_features,train_labels)
    validation_predictions=pruned_classifier.predict(validation_features)
    validation_accuracy=accuracy(validation_predictions,validation_labels)
    if validation_accuracy>best_accuracy:
      best_accuracy=validation_accuracy
      best_model=pruned_classifier
    print("The accuracy of the model {} split and {} leaf on the validation set is {:.2f}%".format(split,leaf, validation_accuracy))

import pickle
#The should result in a file on your Google Drive Folder on the right
with open("dt_model_Forrest.pkl","wb") as file:
  pickle.dump(best_model,file)

"""**[5 points] Extra Credit**

Complete the recrusive function below to build a Decision Tree. You will make use of the information gain function that you implemented here.

##Note: If you attempt this you are expected to explain the code to me in person or in class.
"""

def build_decision_tree(data,attributes,depth):
    """
    Recursively builds a decision tree based on the provided dataset and attributes.

    Args:
    ----------
    data : numpy array


    attributes : list
        A list of attributes (features)

    depth : int
        The current depth of the tree.

    Returns:
    -------
    Tree

    """
    #FILL IN
    return None

"""**Submission Instructions**
- Your submission should include three files, please use your lastname in the place holder. If your last name is Doe then the file for answers will be answers_Doe.txt:

1. Written answers, the file should be named answers_(lastname).txt
2. The ipynb file, the file should be name P1_(lastname).ipynb
3. The decision tree model pickle file dt_model_(lastname).pkl

- Please add comments to the code in appropriate places
- Start Early, Good Luck!
"""